# Generated by Django 3.0 on 2021-10-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo_Hora', models.FloatField(verbose_name='Costo por Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=60)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('complejidad', models.FloatField(verbose_name='Complejidad')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=60)),
                ('descripcion', models.CharField(default='', max_length=500, verbose_name='Descripción')),
                ('tiempo_Estimado', models.FloatField(default=0, verbose_name='Tiempo Estimado en Semanas')),
                ('tiempo_Actual', models.FloatField(default=0)),
                ('costo_Estimado', models.FloatField(default=0, verbose_name='Costo por Estimado ($)')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('tiempo_Estimado', models.FloatField(verbose_name='Tiempo Estimado')),
                ('tiempo_Real', models.FloatField(verbose_name='Tiempo Real Usado')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Catalogo')),
                ('historia_Asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Historia', verbose_name='Proyecto Asociado')),
                ('integrante_Encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Integrante', verbose_name='Encargado')),
            ],
        ),
        migrations.AddField(
            model_name='historia',
            name='integrante_Encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Integrante', verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='historia',
            name='proyecto_Asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Proyecto', verbose_name='Proyecto Asociado'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('integrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Integrante', verbose_name='Encargado')),
                ('proyecto_Asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Proyecto', verbose_name='Proyecto Asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Catalogo')),
                ('historia_Asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Historia', verbose_name='Proyecto Asociado')),
                ('integrante_Encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Integrante', verbose_name='Encargado')),
            ],
        ),
    ]
