# Generated by Django 3.0 on 2021-10-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('FechaNacimiento', models.DateField()),
                ('Usuario', models.CharField(max_length=40)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
