# Generated by Django 3.0 on 2021-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
    ]
