# Generated by Django 3.0 on 2021-11-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
