# Generated by Django 3.0 on 2021-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
