# Generated by Django 3.0 on 2021-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0002_auto_20211024_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='capacidad',
            field=models.FloatField(default=0, verbose_name='Capacidad Integrante'),
        ),
    ]
