# Generated by Django 3.0 on 2021-11-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0002_auto_20211102_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='integrante',
        ),
        migrations.AddField(
            model_name='integrante',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Equipo'),
        ),
    ]
