# Generated by Django 3.0 on 2021-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0003_auto_20211103_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='contrasena',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
    ]
