# Generated by Django 3.0 on 2021-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0004_auto_20211103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
