# Generated by Django 3.0 on 2021-11-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0005_auto_20211103_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='integrante_Encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Integrante', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='proyecto_Asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Proyecto', verbose_name='Proyecto Asociado'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='integrante_Encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Integrante', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Equipo'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Rol'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Estado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='integrante_Encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Integrante', verbose_name='Encargado'),
        ),
    ]
