# Generated by Django 3.0 on 2021-11-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0006_auto_20211107_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Estado'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Estado'),
        ),
    ]
