# Generated by Django 3.0 on 2021-11-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0007_auto_20211107_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='proyecto_Asociado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo_Asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionUsuarios.Equipo', verbose_name='Equipo Asociado'),
        ),
    ]
