# Generated by Django 3.2.9 on 2021-11-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0008_auto_20211113_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiempos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Ideal', models.DateField()),
                ('tiempo_Ideal', models.FloatField()),
                ('fecha_Actual', models.DateField(null=True)),
                ('tiempo_Actual', models.FloatField()),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.proyecto')),
            ],
        ),
    ]
