# Generated by Django 3.2.9 on 2021-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0009_tiempos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempos',
            name='tiempo_Actual',
            field=models.FloatField(null=True),
        ),
    ]
