# Generated by Django 3.2.9 on 2021-11-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0010_alter_tiempos_tiempo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempos',
            name='proyecto_id',
            field=models.IntegerField(),
        ),
    ]
