# Generated by Django 3.2.9 on 2021-12-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0013_auto_20211128_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tiempo_estimado',
            field=models.FloatField(default=0, verbose_name='Tiempo Estimado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_usado',
            field=models.FloatField(default=0, verbose_name='Tiempo Usado'),
            preserve_default=False,
        ),
    ]
